// lib/translate.ts

const urduDictionary: Record<string, string> = {
  "the": "یہ",
  "a": "ایک",
  "and": "اور",
  "is": "ہے",
  "was": "تھا",
  "in": "میں",
  "on": "پر",
  "for": "کے لیے",
  "of": "کا",
  "with": "کے ساتھ",
  "to": "کی طرف",
  "by": "کی طرف سے",
  "as": "جیسا کہ",
  "that": "وہ",
  "this": "یہ",
  "it": "یہ",
  "are": "ہیں",
  "be": "ہونا",
  "have": "رکھنا",
  "has": "ہے",
  "at": "پر",
  "from": "سے",
  "or": "یا",
  "an": "ایک",
  "will": "کرے گا",
  "not": "نہیں",
  "can": "سکتا ہے",
  "we": "ہم",
  "they": "وہ",
  "he": "وہ",
  "she": "وہ",
  "you": "آپ",
  "i": "میں",
  "his": "اس کا",
  "her": "اس کی",
  "their": "ان کا",
  "our": "ہمارا",
  "its": "اس کا",
  "blog": "بلاگ",
  "article": "مضمون",
  "content": "مواد",
  "summary": "خلاصہ",
  "translate": "ترجمہ کرنا",
  "translation": "ترجمہ",
  "english": "انگریزی",
  "urdu": "اردو",
  "language": "زبان",
  "simple": "سادہ",
  "text": "متن",
  "read": "پڑھنا",
  "write": "لکھنا",
  "click": "کلک کریں",
  "submit": "جمع کرائیں",
  "search": "تلاش",
  "information": "معلومات",
  "user": "صارف",
  "data": "ڈیٹا",
  "summary:": "خلاصہ:",
  "sentence": "جملہ",
  "weather": "موسم",
  "cold": "سرد",
  "hot": "گرم",
  "sun": "سورج",
  "rain": "بارش",
  "man": "آدمی",
  "woman": "عورت",
  "old": "پرانا",
  "new": "نیا",
  "time": "وقت",
  "day": "دن",
  "night": "رات",
  "people": "لوگ",
  "world": "دنیا",
  "life": "زندگی",
  "use": "استعمال",
  "make": "بنانا",
  "do": "کرنا",
  "build": "بنائیں",
  "example": "مثال",
  "easy": "آسان",
  "difficult": "مشکل",
  "ai": "مصنوعی ذہانت",
  "chatgpt": "چیٹ جی پی ٹی",
  "openai": "اوپن اے آئی",
  "project": "منصوبہ",
  "code": "کوڈ",
  "tool": "اوزار",
  "blogger": "بلاگر",
  "writer": "لکھاری",
  "developer": "ڈویلپر",
  "summary (english):": "خلاصہ (انگریزی):",
  "summary (urdu):": "خلاصہ (اردو):"
};

export function translateToUrdu(text: string): string {
  return text
    .split(' ')
    .map(word => {
      // Remove punctuation for better matching
      const cleanWord = word.toLowerCase().replace(/[.,!?]/g, '');
      return urduDictionary[cleanWord] || word;
    })
    .join(' ');
}
